### ISSUE TITLE
Can not run server.js

### ISSUE THREAD

**Issue by Ndh474** [elhadjx/meowbot#4]
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'conversations/conversations.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at readConv (D:\Download\meowbot-main\server.js:299:29)
    at Object.<anonymous> (D:\Download\meowbot-main\server.js:23:21)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'conversations/conversations.json'
}
when i run, it happened, pls help me solve it!

**Comment by elhadjx** [comment]
create a directory "conversations" then create a file "conversations.json".
in the json file put this
`[]`
because it's an array ( empty for now)

**Comment by Ndh474** [comment]
> create a directory "conversations" then create a file "conversations.json". in the json file put this `[]` because it's an array ( empty for now)

thank, but after did it, i had new issue:
  const conversations = obj.table.filter(element => {
                                  ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at readConv (D:\Download\meowbot-main\server.js:302:35)
    at Object.<anonymous> (D:\Download\meowbot-main\server.js:23:21)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
    how can i solve it?
